export const ORDER_CREATED= "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
export const ORDER_CANCELED = "ORDER_CANCELED";
export const ORDER_DISCOUNTED= "ORDER_DISCOUNTED";
export const ORDER_PAYED= "ORDER_PAYED";
export const ORDER_OITEM_ADDED= "ORDER_OITEM_ADDED";
export const ORDER_OITEM_REMOVED= "ORDER_OITEM_REMOVE";
export const ORDER_OITEM_GSTMODIFIED= "ORDER_OITEM_GSTMODIFIED";

export const USER_ADDED = "USER_ADDED";
export const USER_REMOVED = "USER_REMOVED";
export const USER_MODIFIED = "USER_MODIFIED";
export const FILTER_CHANGED_ROLE="FILTER_CHANGE_ROLE";


export const LOGIN_BEGINS = "LOGIN_BEGINS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";


//global actions
export const FILTER_CHANGE_NAME="FILTER_CHANGE_NAME";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE"
